import os

JWT_ISSUER=os.getenv("JWT_ISSUER")
JWT_AUDIENCE=os.getenv("JWT_AUDIENCE")
ACCESS_JWT_SECRET_KEY=os.getenv("ACCESS_JWT_SECRET_KEY")
REFRESH_JWT_SECRET_KEY=os.getenv("REFRESH_JWT_SECRET_KEY")
TOKEN_ALGORITHM=os.getenv("TOKEN_ALGORITHM")
DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES=os.getenv("DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES")
DEFAULT_REFRESH_TOKEN_EXPIRE_MINUTES=os.getenv("DEFAULT_REFRESH_TOKEN_EXPIRE_MINUTES")
DOMAIN=os.getenv("DOMAIN") # Needs to have a trailing "/":  eg) "https://api.example.com/"